<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.Petmodules</groupId>
  <artifactId>UberPetStore</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
 
   <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>4.0.1</serenity.version>
        <serenity.maven.version>4.0.1</serenity.maven.version>
        <webdriver.driver.version>4.10.0</webdriver.driver.version>
        <serenity.cucumber>4.0.30</serenity.cucumber>
        <webdriver.driver>firefox</webdriver.driver>
    </properties>


  <dependencies>
    <dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
    <version>1.68</version>
    
       </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>     
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
			<groupId>net.serenity-bdd</groupId>
			<artifactId>serenity-junit</artifactId>
			<version>${serenity.version}</version>
		</dependency>
          <!-- https://mvnrepository.com/artifact/net.serenity-bdd/serenity-rest-assured -->
	  <!-- https://mvnrepository.com/artifact/net.serenity-bdd/serenity-rest-assured -->
		<dependency>
    		<groupId>net.serenity-bdd</groupId>
    		<artifactId>serenity-rest-assured</artifactId>
    		<version>4.0.1</version>
		</dependency>
		<dependency>
   			 <groupId>com.googlecode.json-simple</groupId>
    		<artifactId>json-simple</artifactId>
    		<version>1.1.1</version> <!-- Use the latest version available -->
		</dependency>
		 <dependency>
        	<groupId>io.rest-assured</groupId>
        	<artifactId>rest-assured</artifactId>
        	<version>5.3.1</version>
        	<scope>test</scope>
    	</dependency>
		<!-- https://mvnrepository.com/artifact/net.serenity-bdd/serenity-cucumber -->
	<dependency>
   		<groupId>net.serenity-bdd</groupId>
    	<artifactId>serenity-cucumber</artifactId>
    	<version>${serenity.cucumber}</version>
    	<scope>test</scope>
	</dependency>
	<!-- https://mvnrepository.com/artifact/org.assertj/assertj-core -->
	<!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind -->
		<dependency>
    	<groupId>com.fasterxml.jackson.core</groupId>
    	<artifactId>jackson-databind</artifactId>
    	<version>2.17.1</version>
	</dependency>
	<dependency>
   		 <groupId>com.fasterxml.jackson.core</groupId>
    	<artifactId>jackson-annotations</artifactId>
    	<version>2.17.1</version>
	</dependency>
	<dependency>
    	<groupId>com.fasterxml.jackson.core</groupId>
    	<artifactId>jackson-core</artifactId>
    	<version>2.17.1</version>
	</dependency>

<!-- Source: https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml -->
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml</artifactId>
    <version>5.5.1</version>
    <scope>compile</scope>
</dependency>


 

	<dependency>
    <groupId>org.assertj</groupId>
    <artifactId>assertj-core</artifactId>
    <version>3.20.2</version>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.7.0</version>
    <scope>test</scope>
</dependency>
	<!-- https://mvnrepository.com/artifact/com.google.code.gson/gson -->
	<dependency>
    	<groupId>com.google.code.gson</groupId>
    	<artifactId>gson</artifactId>
   	 <version>2.10.1</version>
	</dependency>

	<!-- https://mvnrepository.com/artifact/org.webjars.npm/selenium-webdriver -->
	<dependency>
    	<groupId>org.webjars.npm</groupId>
    	<artifactId>selenium-webdriver</artifactId>
    	<version>${webdriver.driver.version}</version>
	</dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.6.1</version>
        </dependency>
        
        <!-- Source: https://mvnrepository.com/artifact/com.github.javafaker/javafaker -->
<dependency>
    <groupId>com.github.javafaker</groupId>
    <artifactId>javafaker</artifactId>
    <version>1.0.1</version>
    <scope>compile</scope>
</dependency>

<!-- Source: https://mvnrepository.com/artifact/org.apache.poi/poi -->
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi</artifactId>
    <version>5.5.1</version>
    <scope>compile</scope>
</dependency>

<!-- Source: https://mvnrepository.com/artifact/commons-io/commons-io -->
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.19.0</version>
   
</dependency>

<!-- Source: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core -->
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>2.25.3</version>
    <scope>compile</scope>
</dependency>

<dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.26.1</version> <!-- Use a recent, compatible version -->
        </dependency>

       
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        
        
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.25.0</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
			<groupId>com.googlecode.lambdaj</groupId>
			<artifactId>lambdaj</artifactId>
			<version>2.3.3</version>
		</dependency>
		<!-- API, java.xml.bind module -->
	<dependency>
    	<groupId>jakarta.xml.bind</groupId>
    	<artifactId>jakarta.xml.bind-api</artifactId>
    	<version>2.3.2</version>
	</dependency>
	<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.16.1</version>
</dependency>
	<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20210307</version> <!-- or the latest version -->
</dependency>
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.5.0</version>
    <scope>test</scope>
</dependency>


<!-- Runtime, com.sun.xml.bind module -->
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.2</version>
</dependency>
    </dependencies>
   
    <build>
        <plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.18</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>                  
                <version>2.18</version>
                <configuration>
                    <includes>						 
						<include>**/TestRunner.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
						<goals>
							<goal>integration-test</goal>
							<goal>verify</goal>
						</goals>
					</execution>
                </executions>
            </plugin>
            <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
			    	<source>11</source>
					<target>11</target>
				<suiteXmlFiles>
				<suiteXmlFile>Usertestng.xml</suiteXmlFile>
				</suiteXmlFiles>
				</configuration>
			</plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>       
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                     <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                    </dependency>
                </dependencies>
                <executions>
             	<execution>
						<id>serenity-reports</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>aggregate</goal>
						</goals>
					</execution>
                </executions>
            </plugin>
        </plugins>
    </build>
  
</project>